version: '3.8'

x-app: &app
  build:
    context: .
    dockerfile: Dockerfile
  environment: &env
    NODE_ENV: development
    RAILS_ENV: ${RAILS_ENV:-development}
  image: dev:1.0.0
  tmpfs:
    - /tmp

x-backend: &backend
  <<: *app
  stdin_open: true
  tty: true
  volumes:
    - .:/app:cached
    - rails_cache:/app/tmp/cache
    - bundle:/usr/local/bundle
    - node_modules:/app/node_modules
    - ~/.gitconfig:/root/.gitconfig
  environment:
    <<: *env
    DATABASE_URL: postgres://postgres:postgres@postgres:5432
    BOOTSNAP_CACHE_DIR: /usr/local/bundle/_bootsnap
    HISTFILE: /app/log/.history
    PSQL_HISTFILE: /app/log/.psql_history
  depends_on:
    postgres:
      condition: service_healthy

services:
  rails:
    <<: *backend
    command: /bin/sh -c 'rm -f tmp/pids/server.pid && bin/dev'
    ports:
      - '3000:3000'
      - '35729:35729'

  postgres:
    image: postgres:13.6-alpine3.15
    volumes:
      - postgres:/var/lib/postgresql/data
      - ./log:/root/log:cached
    environment:
      PSQL_HISTFILE: /root/log/.psql_history
      POSTGRES_PASSWORD: postgres
    ports:
      - 5432
    healthcheck:
      test: pg_isready -U postgres -h 127.0.0.1
      interval: 5s

volumes:
  postgres:
  bundle:
  node_modules:
  rails_cache:
